//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiveGameWPFApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiveGameWPFApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string btn_CreateAccount {
            get {
                return ResourceManager.GetString("btn_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string btn_Guest {
            get {
                return ResourceManager.GetString("btn_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string btn_SendMessage {
            get {
                return ResourceManager.GetString("btn_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action confirmation.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been successfully created. Welcome! :D.
        /// </summary>
        public static string dialogAccountCreated {
            get {
                return ResourceManager.GetString("dialogAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to establish a connection with the server. Please check your internet connection and try it again..
        /// </summary>
        public static string dialogComunicationException {
            get {
                return ResourceManager.GetString("dialogComunicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred with the database, please try again..
        /// </summary>
        public static string dialogDataBaseError {
            get {
                return ResourceManager.GetString("dialogDataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to find the endpoint. Please check the server configuration and try again..
        /// </summary>
        public static string dialogEndPointException {
            get {
                return ResourceManager.GetString("dialogEndPointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email or username to regist are already registered..
        /// </summary>
        public static string dialogExistinAccount {
            get {
                return ResourceManager.GetString("dialogExistinAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to exit?.
        /// </summary>
        public static string dialogExitMainMenu {
            get {
                return ResourceManager.GetString("dialogExitMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has joined to the lobby. Give it a welcome! .
        /// </summary>
        public static string dialogMessageJoinChat {
            get {
                return ResourceManager.GetString("dialogMessageJoinChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to find the account. Please verify to type the correct email and password..
        /// </summary>
        public static string dialogMissmatchesCredentials {
            get {
                return ResourceManager.GetString("dialogMissmatchesCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify that the password that you typed are the same..
        /// </summary>
        public static string dialogMissmatchesPassword {
            get {
                return ResourceManager.GetString("dialogMissmatchesPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no modifications to do, if you want to modify your profile, change any field..
        /// </summary>
        public static string dialogSameDataProfileModification {
            get {
                return ResourceManager.GetString("dialogSameDataProfileModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try again waiting time has expired. Please check your connection to the server..
        /// </summary>
        public static string dialogTimeOutException {
            get {
                return ResourceManager.GetString("dialogTimeOutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action confirmation.
        /// </summary>
        public static string dialogTitleConfirmation {
            get {
                return ResourceManager.GetString("dialogTitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred.
        /// </summary>
        public static string dialogTitleError {
            get {
                return ResourceManager.GetString("dialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation succesfull.
        /// </summary>
        public static string dialogTitleSucces {
            get {
                return ResourceManager.GetString("dialogTitleSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string dialogTitleWarning {
            get {
                return ResourceManager.GetString("dialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information has been modified successfully..
        /// </summary>
        public static string dialogUpdatedData {
            get {
                return ResourceManager.GetString("dialogUpdatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information that you type is incorrect, try it again..
        /// </summary>
        public static string dialogWrongData {
            get {
                return ResourceManager.GetString("dialogWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string globalbtn_Confirm {
            get {
                return ResourceManager.GetString("globalbtn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalLbl_Email {
            get {
                return ResourceManager.GetString("globalLbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string globalLbl_Password {
            get {
                return ResourceManager.GetString("globalLbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User name.
        /// </summary>
        public static string globalLbl_UserName {
            get {
                return ResourceManager.GetString("globalLbl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string lbl_ConfirmPassword {
            get {
                return ResourceManager.GetString("lbl_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Account.
        /// </summary>
        public static string lbl_CreateAccount {
            get {
                return ResourceManager.GetString("lbl_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string lbl_Description {
            get {
                return ResourceManager.GetString("lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Profile.
        /// </summary>
        public static string lbl_EditProfile {
            get {
                return ResourceManager.GetString("lbl_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string lbl_Nickname {
            get {
                return ResourceManager.GetString("lbl_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Picture.
        /// </summary>
        public static string lbl_ProfilePicture {
            get {
                return ResourceManager.GetString("lbl_ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string lbl_RecoverPassword {
            get {
                return ResourceManager.GetString("lbl_RecoverPassword", resourceCulture);
            }
        }
    }
}
