//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiveGameWPFApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HiveGameWPFApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acept.
        /// </summary>
        public static string btn_Acept {
            get {
                return ResourceManager.GetString("btn_Acept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add friend.
        /// </summary>
        public static string btn_Add {
            get {
                return ResourceManager.GetString("btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string btn_CreateAccount {
            get {
                return ResourceManager.GetString("btn_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create match.
        /// </summary>
        public static string btn_CreateMatch {
            get {
                return ResourceManager.GetString("btn_CreateMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Decline.
        /// </summary>
        public static string btn_Decline {
            get {
                return ResourceManager.GetString("btn_Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string btn_Delete {
            get {
                return ResourceManager.GetString("btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Credentials.
        /// </summary>
        public static string btn_EditCredentials {
            get {
                return ResourceManager.GetString("btn_EditCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Profile.
        /// </summary>
        public static string btn_EditProfile {
            get {
                return ResourceManager.GetString("btn_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string btn_Friend {
            get {
                return ResourceManager.GetString("btn_Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend requests.
        /// </summary>
        public static string btn_FriendRequest {
            get {
                return ResourceManager.GetString("btn_FriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend games.
        /// </summary>
        public static string btn_GameFriends {
            get {
                return ResourceManager.GetString("btn_GameFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go back.
        /// </summary>
        public static string btn_GoBack {
            get {
                return ResourceManager.GetString("btn_GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string btn_Guest {
            get {
                return ResourceManager.GetString("btn_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join match.
        /// </summary>
        public static string btn_JoinMatch {
            get {
                return ResourceManager.GetString("btn_JoinMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join the Game.
        /// </summary>
        public static string btn_JoinTheGame {
            get {
                return ResourceManager.GetString("btn_JoinTheGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log in.
        /// </summary>
        public static string btn_Login {
            get {
                return ResourceManager.GetString("btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a My Account.
        /// </summary>
        public static string btn_MyAccount {
            get {
                return ResourceManager.GetString("btn_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Play.
        /// </summary>
        public static string btn_Play {
            get {
                return ResourceManager.GetString("btn_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string btn_Search {
            get {
                return ResourceManager.GetString("btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string btn_Send {
            get {
                return ResourceManager.GetString("btn_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send off player.
        /// </summary>
        public static string btn_SendOffPlayer {
            get {
                return ResourceManager.GetString("btn_SendOffPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string btn_Start {
            get {
                return ResourceManager.GetString("btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics.
        /// </summary>
        public static string btn_Statistics {
            get {
                return ResourceManager.GetString("btn_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action confirmation.
        /// </summary>
        public static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend request has been accepted.
        /// </summary>
        public static string dialogAcceptFriendRequest {
            get {
                return ResourceManager.GetString("dialogAcceptFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your account has been successfully created. Welcome! :D.
        /// </summary>
        public static string dialogAccountCreated {
            get {
                return ResourceManager.GetString("dialogAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t add yourself as a friend..
        /// </summary>
        public static string dialogCanNotAddYourself {
            get {
                return ResourceManager.GetString("dialogCanNotAddYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to establish a connection with the server. Please check your internet connection and try it again..
        /// </summary>
        public static string dialogComunicationException {
            get {
                return ResourceManager.GetString("dialogComunicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to kick this player?.
        /// </summary>
        public static string dialogConfirmationKickPlayer {
            get {
                return ResourceManager.GetString("dialogConfirmationKickPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to create a new match?.
        /// </summary>
        public static string dialogConfirmationMatchCreation {
            get {
                return ResourceManager.GetString("dialogConfirmationMatchCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to delete this friend?.
        /// </summary>
        public static string dialogConfirmFriendDelete {
            get {
                return ResourceManager.GetString("dialogConfirmFriendDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to leave the lobby?.
        /// </summary>
        public static string dialogConfirmLeaveLobby {
            get {
                return ResourceManager.GetString("dialogConfirmLeaveLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We couldn´t find you user account, try to text the correct username or email..
        /// </summary>
        public static string dialogCouldntFindUserAccount {
            get {
                return ResourceManager.GetString("dialogCouldntFindUserAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t find user session .
        /// </summary>
        public static string dialogCouldntFindUserSession {
            get {
                return ResourceManager.GetString("dialogCouldntFindUserSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t discconect the player from the lobby, try it again..
        /// </summary>
        public static string dialogCouldntLobbyDisconnection {
            get {
                return ResourceManager.GetString("dialogCouldntLobbyDisconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There has been an error while sending email message. Try it again..
        /// </summary>
        public static string dialogCouldntSendEmail {
            get {
                return ResourceManager.GetString("dialogCouldntSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred with the database, please try again..
        /// </summary>
        public static string dialogDataBaseError {
            get {
                return ResourceManager.GetString("dialogDataBaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend request has been decline..
        /// </summary>
        public static string dialogDeclinedFriendRequest {
            get {
                return ResourceManager.GetString("dialogDeclinedFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email that you want to save, is already registered in another account..
        /// </summary>
        public static string dialogEmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("dialogEmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The invitation has been send to the user selected..
        /// </summary>
        public static string dialogEmailInvitationSend {
            get {
                return ResourceManager.GetString("dialogEmailInvitationSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email sended. Please check your email account in order to see the verification code..
        /// </summary>
        public static string dialogEmailVerificationMessage {
            get {
                return ResourceManager.GetString("dialogEmailVerificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Failed to find the endpoint. Please check the server configuration and try again..
        /// </summary>
        public static string dialogEndPointException {
            get {
                return ResourceManager.GetString("dialogEndPointException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error at obtaining profile user data..
        /// </summary>
        public static string dialogErrorAtObtainingUserData {
            get {
                return ResourceManager.GetString("dialogErrorAtObtainingUserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t close users session, please try again..
        /// </summary>
        public static string dialogErrorInDisconnection {
            get {
                return ResourceManager.GetString("dialogErrorInDisconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The email or username to regist are already registered..
        /// </summary>
        public static string dialogExistinAccount {
            get {
                return ResourceManager.GetString("dialogExistinAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can&apos;t join the game, the same account is playing on another device..
        /// </summary>
        public static string dialogExistingSession {
            get {
                return ResourceManager.GetString("dialogExistingSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to exit?.
        /// </summary>
        public static string dialogExitMainMenu {
            get {
                return ResourceManager.GetString("dialogExitMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your friend has been deleted.
        /// </summary>
        public static string dialogFriendDeleted {
            get {
                return ResourceManager.GetString("dialogFriendDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The friend request has been sended succesfully..
        /// </summary>
        public static string dialogFriendRequestSended {
            get {
                return ResourceManager.GetString("dialogFriendRequestSended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sorry, the lobby that you want to join is already full..
        /// </summary>
        public static string dialogFullLobby {
            get {
                return ResourceManager.GetString("dialogFullLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The host of the lobby has left, you will be redirected to the main menu..
        /// </summary>
        public static string dialogHostHasLeft {
            get {
                return ResourceManager.GetString("dialogHostHasLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The person that you want to search is not online..
        /// </summary>
        public static string dialogMangerCouldntFindFriend {
            get {
                return ResourceManager.GetString("dialogMangerCouldntFindFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a has joined to the lobby. Give it a welcome! .
        /// </summary>
        public static string dialogMessageJoinChat {
            get {
                return ResourceManager.GetString("dialogMessageJoinChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unable to find the account. Please verify to type the correct email and password..
        /// </summary>
        public static string dialogMissmatchesCredentials {
            get {
                return ResourceManager.GetString("dialogMissmatchesCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verify that the password that you typed are the same..
        /// </summary>
        public static string dialogMissmatchesPassword {
            get {
                return ResourceManager.GetString("dialogMissmatchesPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no friend requests to show..
        /// </summary>
        public static string dialogNoFriendRequest {
            get {
                return ResourceManager.GetString("dialogNoFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no friends added, try to find new friends. :D.
        /// </summary>
        public static string dialogNoFriendsAdded {
            get {
                return ResourceManager.GetString("dialogNoFriendsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Couldn&apos;t find the specific personal leaderboard..
        /// </summary>
        public static string dialogNoPersonalLeaderboard {
            get {
                return ResourceManager.GetString("dialogNoPersonalLeaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The code for the match that you type, does not exist, verify and try it again..
        /// </summary>
        public static string dialogNotExistingCode {
            get {
                return ResourceManager.GetString("dialogNotExistingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The username that you type does not exist. Try again..
        /// </summary>
        public static string dialogNoUsernameFound {
            get {
                return ResourceManager.GetString("dialogNoUsernameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There are no modifications to do, if you want to modify your profile, change any field..
        /// </summary>
        public static string dialogSameDataProfileModification {
            get {
                return ResourceManager.GetString("dialogSameDataProfileModification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Try again waiting time has expired. Please check your connection to the server..
        /// </summary>
        public static string dialogTimeOutException {
            get {
                return ResourceManager.GetString("dialogTimeOutException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Action confirmation.
        /// </summary>
        public static string dialogTitleConfirmation {
            get {
                return ResourceManager.GetString("dialogTitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An error has ocurred.
        /// </summary>
        public static string dialogTitleError {
            get {
                return ResourceManager.GetString("dialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Operation succesfull.
        /// </summary>
        public static string dialogTitleSucces {
            get {
                return ResourceManager.GetString("dialogTitleSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Warning.
        /// </summary>
        public static string dialogTitleWarning {
            get {
                return ResourceManager.GetString("dialogTitleWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information has been modified successfully..
        /// </summary>
        public static string dialogUpdatedData {
            get {
                return ResourceManager.GetString("dialogUpdatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The information that you type is incorrect, try it again..
        /// </summary>
        public static string dialogWrongData {
            get {
                return ResourceManager.GetString("dialogWrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have been kick from the lobby..
        /// </summary>
        public static string dialogYouveBeenKick {
            get {
                return ResourceManager.GetString("dialogYouveBeenKick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string globalbtn_Cancel {
            get {
                return ResourceManager.GetString("globalbtn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string globalbtn_Confirm {
            get {
                return ResourceManager.GetString("globalbtn_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partial discconnection, couldn´t disconnect the player at all..
        /// </summary>
        public static string globalDialog_PartialDisconnection {
            get {
                return ResourceManager.GetString("globalDialog_PartialDisconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string globalLbl_Email {
            get {
                return ResourceManager.GetString("globalLbl_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string globalLbl_Password {
            get {
                return ResourceManager.GetString("globalLbl_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remeber that your password must contain at least 8 characters. Including at least 1 number, 1 capital letter, 1 lowercase letter and 1 special character..
        /// </summary>
        public static string globalLbl_PasswordIndications {
            get {
                return ResourceManager.GetString("globalLbl_PasswordIndications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User name.
        /// </summary>
        public static string globalLbl_UserName {
            get {
                return ResourceManager.GetString("globalLbl_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remember that your password must contain at least 8 characters. Including at least 1 number, 1 capital letter, 1 lowercase letter and 1 special character..
        /// </summary>
        public static string globalTxtb_PasswordIndications {
            get {
                return ResourceManager.GetString("globalTxtb_PasswordIndications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We have send a code to your email, please verify it and type it. .
        /// </summary>
        public static string lbl_CodeSendMessage {
            get {
                return ResourceManager.GetString("lbl_CodeSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm Password.
        /// </summary>
        public static string lbl_ConfirmPassword {
            get {
                return ResourceManager.GetString("lbl_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Account.
        /// </summary>
        public static string lbl_CreateAccount {
            get {
                return ResourceManager.GetString("lbl_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string lbl_Description {
            get {
                return ResourceManager.GetString("lbl_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit credentials.
        /// </summary>
        public static string lbl_EditCredentials {
            get {
                return ResourceManager.GetString("lbl_EditCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edit Profile.
        /// </summary>
        public static string lbl_EditProfile {
            get {
                return ResourceManager.GetString("lbl_EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string lbl_Friends {
            get {
                return ResourceManager.GetString("lbl_Friends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Game Code.
        /// </summary>
        public static string lbl_GameCode {
            get {
                return ResourceManager.GetString("lbl_GameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lenguage.
        /// </summary>
        public static string lbl_Lenguage {
            get {
                return ResourceManager.GetString("lbl_Lenguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Losses.
        /// </summary>
        public static string lbl_Losses {
            get {
                return ResourceManager.GetString("lbl_Losses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music.
        /// </summary>
        public static string lbl_Music {
            get {
                return ResourceManager.GetString("lbl_Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string lbl_Name {
            get {
                return ResourceManager.GetString("lbl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New password.
        /// </summary>
        public static string lbl_NewPassword {
            get {
                return ResourceManager.GetString("lbl_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nickname.
        /// </summary>
        public static string lbl_Nickname {
            get {
                return ResourceManager.GetString("lbl_Nickname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No friends added yet.
        /// </summary>
        public static string lbl_NoFriends {
            get {
                return ResourceManager.GetString("lbl_NoFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You didn&apos;t received the code?.
        /// </summary>
        public static string lbl_NoReceivedCode {
            get {
                return ResourceManager.GetString("lbl_NoReceivedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personal.
        /// </summary>
        public static string lbl_Personal {
            get {
                return ResourceManager.GetString("lbl_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Profile Picture.
        /// </summary>
        public static string lbl_ProfilePicture {
            get {
                return ResourceManager.GetString("lbl_ProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot your password?.
        /// </summary>
        public static string lbl_RecoverPassword {
            get {
                return ResourceManager.GetString("lbl_RecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover your password.
        /// </summary>
        public static string lbl_RecoverYourPassword {
            get {
                return ResourceManager.GetString("lbl_RecoverYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resend code.
        /// </summary>
        public static string lbl_ResendCode {
            get {
                return ResourceManager.GetString("lbl_ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Statistics.
        /// </summary>
        public static string lbl_Statistics {
            get {
                return ResourceManager.GetString("lbl_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recover Password.
        /// </summary>
        public static string lbl_TitleRecoverPassword {
            get {
                return ResourceManager.GetString("lbl_TitleRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total Games.
        /// </summary>
        public static string lbl_TotalGames {
            get {
                return ResourceManager.GetString("lbl_TotalGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email:.
        /// </summary>
        public static string lbl_UserEmail {
            get {
                return ResourceManager.GetString("lbl_UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wins.
        /// </summary>
        public static string lbl_Wins {
            get {
                return ResourceManager.GetString("lbl_Wins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a World.
        /// </summary>
        public static string lbl_World {
            get {
                return ResourceManager.GetString("lbl_World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Wrong verification code.
        /// </summary>
        public static string lbl_WrondVerificationCode {
            get {
                return ResourceManager.GetString("lbl_WrondVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You can resend a new code in .
        /// </summary>
        public static string txt_Timer {
            get {
                return ResourceManager.GetString("txt_Timer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest.
        /// </summary>
        public static string txtb_Guest {
            get {
                return ResourceManager.GetString("txtb_Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guest name.
        /// </summary>
        public static string txtb_GuestName {
            get {
                return ResourceManager.GetString("txtb_GuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host.
        /// </summary>
        public static string txtb_Host {
            get {
                return ResourceManager.GetString("txtb_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host name.
        /// </summary>
        public static string txtb_HostName {
            get {
                return ResourceManager.GetString("txtb_HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Offline.
        /// </summary>
        public static string txtbl_Disconnected {
            get {
                return ResourceManager.GetString("txtbl_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online.
        /// </summary>
        public static string txtbl_Online {
            get {
                return ResourceManager.GetString("txtbl_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player One.
        /// </summary>
        public static string txtbl_Player1 {
            get {
                return ResourceManager.GetString("txtbl_Player1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player Two.
        /// </summary>
        public static string txtbl_Player2 {
            get {
                return ResourceManager.GetString("txtbl_Player2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turn of:.
        /// </summary>
        public static string txtbl_TurnOf {
            get {
                return ResourceManager.GetString("txtbl_TurnOf", resourceCulture);
            }
        }
    }
}
